# Generated by Django 3.0.3 on 2020-03-07 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200211_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Boi',
            field=models.TextField(default='Add here'),
        ),
    ]
