# Generated by Django 3.0.2 on 2020-02-04 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_auto_20200204_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='blog_image',
            field=models.ImageField(default='default.jpg', upload_to='blog_pics/'),
        ),
    ]
