# Generated by Django 3.0.2 on 2020-02-04 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_post_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_image',
            field=models.ImageField(default='default_1.jpg', upload_to='blog_pics'),
        ),
    ]
