# Generated by Django 3.0.2 on 2020-02-10 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_auto_20200204_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='attractiv_lines',
            field=models.CharField(default='This is attractive lines that attract the people ', max_length=500),
        ),
        migrations.AddField(
            model_name='post',
            name='blog_image_1',
            field=models.ImageField(default='default.jpg', upload_to='blog_pics'),
        ),
        migrations.AddField(
            model_name='post',
            name='sub_title',
            field=models.CharField(default='This is the subtitle of the post ', max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='blog_image',
            field=models.ImageField(default='default.jpg', upload_to='blog_pics'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
