# Generated by Django 3.0.2 on 2020-02-10 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_auto_20200210_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='attractiv_lines',
            field=models.TextField(default='This is attractive lines that attract the people ', max_length=1000),
        ),
    ]
