# Generated by Django 3.0.2 on 2020-02-13 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0007_auto_20200211_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_image_1',
            field=models.ImageField(default='default.jpg', upload_to='media/blog_pics'),
        ),
    ]
