# Generated by Django 3.0.3 on 2020-03-06 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0008_auto_20200213_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_image',
            field=models.ImageField(default='profile_icon.png', upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='post',
            name='blog_image_1',
            field=models.ImageField(default='default.jpg', upload_to='media'),
        ),
    ]
