# Generated by Django 3.0.3 on 2020-03-06 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0009_auto_20200306_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_image',
            field=models.ImageField(default='profile_icon.png', upload_to='blog_pics'),
        ),
        migrations.AlterField(
            model_name='post',
            name='blog_image_1',
            field=models.ImageField(default='default.jpg', upload_to='blog_pics'),
        ),
    ]
